### ISSUE TITLE
[Question] It is possible to disable SCP?

### ISSUE THREAD

**Issue by gabrik** [herlesupreeth/docker_open5gs#148]
First of all, thank you for this very useful project, kudos!

For my PhD work I need to get some "real" payload for some of the procedures, therefore the idea is to run the core network, and capture some traffic over the docker bridge interface.

So far I managed to run the `sa-deploy.yaml` along with the UERANSIM gNB and UE and captured some data. 
But seems that all the communication is being proxy by the SCP.

So I thought to just disable (aka comment) the container from the docker-compose file (and comment all the `depends_on`) and run a capture again. But this time I did not get any HTTP/2 traffic so seems that things are not working.

Edit. Indeed AMF is not happy at all:

<img width="985" alt="Screenshot 2023-02-28 at 19 02 58" src="https://user-images.githubusercontent.com/4215504/221940683-63a5b50b-0e8f-4dca-8a6b-3debce1b3d5c.png">

Here the question, there is a simple way to have a SA deployment without the SCP? 
According to this: https://github.com/open5gs/open5gs/issues/1845 it should be possible, but I guess some configuration is needed for the other network functions. Any suggestion? 

Thank you!

**Comment by herlesupreeth** [comment]
I think it should be possible. Good catch btw, I will fix this right away.

**Comment by herlesupreeth** [comment]
I pushed new commits to address this. Please pull latest commits and give it a try

**Comment by gabrik** [comment]
I'll keep you posted, I guess I need to rebuild the containers right?

**Comment by herlesupreeth** [comment]
No need to rebuild the images. Just restart the docker-compose with SCP disabled

**Comment by gabrik** [comment]
Ok seems that AMF is still not happy:
<img width="451" alt="Screenshot 2023-03-01 at 08 41 15" src="https://user-images.githubusercontent.com/4215504/222077324-b08901af-6992-4c64-957c-1ca2803d47b4.png">
while NRF seems up:
<img width="826" alt="Screenshot 2023-03-01 at 08 53 08" src="https://user-images.githubusercontent.com/4215504/222077537-a7773c96-ae71-415e-b063-bc4b7afbf68d.png">

And in Wireshark I do not see any packet between them just tons of ARP asking for the SCP.
Any suggestion?

**Comment by gabrik** [comment]
Still the same: 
<img width="453" alt="Screenshot 2023-03-01 at 09 04 59" src="https://user-images.githubusercontent.com/4215504/222080033-bbadabcc-1fd4-45a0-b7ce-905dd1966ba2.png">

If you suspect it is a bug in Open5GS I can open an issue there referring to this one

**Comment by herlesupreeth** [comment]
My bad, it was supposed to be `delegated: no`. Eitherway I tested with that as well and still all 5G components are failing so I think its a bug on open5gs

**Comment by gabrik** [comment]
I see then I'll open an issue on the open5gs repo, mentioning this one.
Just for a better understanding the files like `amf.yaml` are the configuration for each network function of the 5G core right?

**Comment by herlesupreeth** [comment]
> Just for a better understanding the files like amf.yaml are the configuration for each network function of the 5G core right?

yep. that is right.

**Comment by gabrik** [comment]
for reference: https://github.com/open5gs/open5gs/issues/2116

**Comment by herlesupreeth** [comment]
I found a solution, rather than commenting out SCP in docker-compose, you can add the following in all the NFs (amf, smf, bsf, udr, udm, pcf, nssf, nrf, ausf, nssf). Then it will use NRF only

```
parameter:
    no_scp: true
```

and use in all above mentioned NFs except NRF

```
    discovery:
      delegated: no
```

**Comment by gabrik** [comment]
Thank you very much for your support! 
I'm going to try it and close this issue when done.

**Comment by gabrik** [comment]
I confirm everything works as expected, I can clearly see from wireshark that the NF communicate between themselves.

Now I would like to contribute this back to your repo.
I guess I can use the .env file to set the `delegated: DELEGATED` and `no_scp: SCP_DISABLED` right?

So in the ENV file I can have `DELEGATED=no` and `SCP_DISABLED=true` and then populate this parameter in the single yaml file for each NF, I guess using the bash file `XXX_init.sh` that is in each folder.

**Comment by sathish-123699** [comment]
im also facing the same issue. i tried commenting out scp section in docker-compose file sa-deploy file. Now all the NF will depend upon NRF only right? 

parameter:
    no_scp: true
    discovery:
      delegated: no
im adding this in all the yaml files of NF.  still it is showing retrying to register with NRF. So by default, the NFs are trying to connect to NRF or SCP in this case?

**Comment by herlesupreeth** [comment]
With the latest commit (f12c344441e444476cf0dda3d66d08cbc9c033f7) in master branch you can remove the scp configuration under sbi client as shown in below amf configuration to disable SCP and use only NRF

```
    sbi:
      server:
        - address: AMF_IP
          port: 7777
      client:
        nrf:
          - uri: http://NRF_IP:7777

```

**Comment by herlesupreeth** [comment]
I see the following in your logs, which suggests that you are not using tag v2.7.0 of open5gs. You need to recompile open5gs base image after switching to latest commits

> amf | Open5GS daemon v2.6.6

**Comment by sathish-123699** [comment]
amf      | 01/30 17:01:33.001: [sbi] ERROR: Connection timer expired (../lib/sbi/client.c:605)
amf      | 01/30 17:01:33.001: [sbi] WARNING: ogs_sbi_client_handler() failed [-3] (../lib/sbi/path.c:62)
amf      | 01/30 17:01:33.002: [sbi] WARNING: [e380ad72-bf62-41ee-a03f-e1bde4c664f5] Retry registration with NRF (../lib/sbi/nf-sm.c:182)
smf      | 01/30 17:01:36.409: [sbi] ERROR: Connection timer expired (../lib/sbi/client.c:605)
smf      | 01/30 17:01:36.410: [sbi] WARNING: ogs_sbi_client_handler() failed [-3] (../lib/sbi/path.c:62)
smf      | 01/30 17:01:36.410: [sbi] WARNING: [e569d370-bf62-41ee-b839-25a6f7fa19af] Retry registration with NRF (../lib/sbi/nf-sm.c:182)
bsf      | 01/30 17:01:41.195: [sbi] ERROR: Connection timer expired (../lib/sbi/client.c:605)
bsf      | 01/30 17:01:41.195: [sbi] WARNING: ogs_sbi_client_handler() failed [-3] (../lib/sbi/path.c:62)
bsf      | 01/30 17:01:41.195: [sbi] WARNING: [e85a5d02-bf62-41ee-8d63-0b7acb5d16d4] Retry registration with NRF (../lib/sbi/nf-sm.c:182)
udr      | 01/30 17:01:42.085: [sbi] ERROR: Connection timer expired (../lib/sbi/client.c:605)
udr      | 01/30 17:01:42.085: [sbi] WARNING: ogs_sbi_client_handler() failed [-3] (../lib/sbi/path.c:62)
udr      | 01/30 17:01:42.086: [sbi] WARNING: [e8e29de8-bf62-41ee-9119-ff2d9fc1aa0e] Retry registration with NRF (../lib/sbi/nf-sm.c:182)
pcf      | 01/30 17:01:42.126: [sbi] ERROR: Connection timer expired (../lib/sbi/client.c:605)
pcf      | 01/30 17:01:42.127: [sbi] WARNING: ogs_sbi_client_handler() failed [-3] (../lib/sbi/path.c:62)
pcf      | 01/30 17:01:42.127: [sbi] WARNING: [e8f0fff0-bf62-41ee-a3ae-7b8e701b4016] Retry registration with NRF (../lib/sbi/nf-sm.c:182)
ausf     | 01/30 17:01:42.189: [sbi] ERROR: Connection timer expired (../lib/sbi/client.c:605)
ausf     | 01/30 17:01:42.189: [sbi] WARNING: ogs_sbi_client_handler() failed [-3] (../lib/sbi/path.c:62)
ausf     | 01/30 17:01:42.190: [sbi] WARNING: [e263a4c6-bf62-41ee-9591-e31fb7c59d37] Retry registration with NRF (../lib/sbi/nf-sm.c:182)
udm      | 01/30 17:01:42.801: [sbi] ERROR: Connection timer expired (../lib/sbi/client.c:605)
udm      | 01/30 17:01:42.801: [sbi] WARNING: ogs_sbi_client_handler() failed [-3] (../lib/sbi/path.c:62)
udm      | 01/30 17:01:42.802: [sbi] WARNING: [e2b413a2-bf62-41ee-874a-d5ae472279ee] Retry registration with NRF (../lib/sbi/nf-sm.c:182)
nssf     | 01/30 17:01:43.237: [sbi] ERROR: Connection timer expired (../lib/sbi/client.c:605)
nssf     | 01/30 17:01:43.237: [sbi] WARNING: ogs_sbi_client_handler() failed [-3] (../lib/sbi/path.c:62)
nssf     | 01/30 17:01:43.238: [sbi] WARNING: [e304507e-bf62-41ee-a95c-31d858ed33d0] Retry registration with NRF (../lib/sbi/nf-sm.c:182)
amf      | 01/30 17:01:44.005: [sbi] ERROR: Connection timer expired (../lib/sbi/client.c:605)
amf      | 01/30 17:01:44.005: [sbi] WARNING: ogs_sbi_client_handler() failed [-3] (../lib/sbi/path.c:62)
amf      | 01/30 17:01:44.005: [sbi] WARNING: [e380ad72-bf62-41ee-a03f-e1bde4c664f5] Retry registration with NRF (../lib/sbi/nf-sm.c:182)
smf      | 01/30 17:01:47.416: [sbi] ERROR: Connection timer expired (../lib/sbi/client.c:605)
smf      | 01/30 17:01:47.416: [sbi] WARNING: ogs_sbi_client_handler() failed [-3] (../lib/sbi/path.c:62)
smf      | 01/30 17:01:47.416: [sbi] WARNING: [e569d370-bf62-41ee-b839-25a6f7fa19af] Retry registration with NRF (../lib/sbi/nf-sm.c:182)


It is showing same error. Retry to register with NRF. 



logger:
    file: /open5gs/install/var/log/open5gs/amf.log

sbi:
    server:
      no_tls: true
    client:
      no_tls: true

global:
  max:
    ue: MAX_NUM_UE

parameter:

amf:
    sbi:
      server:
        - address: AMF_IP
          port: 7777
      client:
        nrf:
          - uri: http://NRF_IP:7777
        # scp:
        #   - uri: http://SCP_IP:7777
    ngap:
      server:
        - address: AMF_IP
    guami:
      - plmn_id:
          mcc: 001
          mnc: 01
        amf_id:
          region: 2
          set: 1
    tai:
      - plmn_id:
          mcc: 001
          mnc: 01
        tac: 1
    plmn_support:
      - plmn_id:
          mcc: 001
          mnc: 01
        s_nssai:
          - sst: 1
    security:
        integrity_order : [ NIA2, NIA1, NIA0 ]
        ciphering_order : [ NEA0, NEA1, NEA2 ]
    network_name:
        full: Open5GS
    amf_name: open5gs-amf0
    metrics:
      server:
        - address: AMF_IP
          port: 9091
    time:
      t3512:
        value: 540

this is my amf.yaml file. I have updated all other yaml files except NRF and SCP. nrf and scp are same as what I downloaded from the repo.  @herlesupreeth is this the problem in open5gs core itself?

**Comment by herlesupreeth** [comment]
[no_scp_diff.txt](https://github.com/herlesupreeth/docker_open5gs/files/14097591/no_scp_diff.txt)

download the file and execute from docker_open5gs folder the following command

`git apply /location_of_downloaded_file/no_scp_diff.txt`

and then run `docker compose -f sa-deploy.yaml up`

**Comment by sathish-123699** [comment]
@herlesupreeth I have freshly installed it in some other computer. There it is working without any errors. Thanks for the help. 
I want to know whether I can do a volte/vonr call by running sa-vonr-deploy.yaml similarly? I have added 2 users in core and Hss as well. Will volte call supported by this repo now?

**Comment by herlesupreeth** [comment]
> I want to know whether I can do a volte/vonr call by running sa-vonr-deploy.yaml similarly? I have added 2 users in core and Hss as well. Will volte call supported by this repo now?

This completely depends on the UE if its allowed to do a VoNR call over default bearer that is used for IMS signalling (usually phones prefer QoS which is achieved via dedicated bearer). Since there is no implementation of N5 interface towards PCF from kamailio P-CSCF there is no way to guarantee QoS for VoNR.

However, you can give it a try for VoNR call since one of the users of repo was able to perform VoNR call between two Samsung phones.
