### ISSUE TITLE
Internet access while using outside eNB with dockerized volte on openstack

### ISSUE THREAD

**Issue by modyngs** [herlesupreeth/docker_open5gs#33]
Dear @herlesupreeth 
Hi,

My topology is 
eNB( is on Local computer)[192.168.1.60] <==========> Openstack VM { Floating Ip add [44.102.129.54] , Docker Host(Openstack vm) [192.168.1.107] , VOLTE_DOCKERized [172.22.xx.xx] } 

1- eNB <===> MME   ))))))))) sucess
2- UE   ))))))))  got connected to network
**3- UE can't access internet while i can see 4G sing in one direction!**

Dockerized CORE is on the openstack vm[192.168.1.107] with default docker ip[172.22. ...] 
eNB is on the Local Coputer with [192.168.1.60]

 
here is attached pcap 
[No Int3.zip](https://github.com/herlesupreeth/docker_open5gs/files/6302989/No.Int3.zip)

in Both sides ipv4 forwarding is enabled!

Thanks 
Best regards

**Comment by modyngs** [comment]
here is the log
[docker logs.txt](https://github.com/herlesupreeth/docker_open5gs/files/6303012/docker.logs.txt)

**Comment by modyngs** [comment]
![Screenshot (78)](https://user-images.githubusercontent.com/82098055/114540080-5d41ec80-9c6a-11eb-8d3d-3476eeb0f4ea.png)

**Comment by herlesupreeth** [comment]
Set SGWU_ADVERTISE_IP to 44.102.129.54 in .env and then do source .env and bring back the stack with docker-compose up and then give it a try

**Comment by modyngs** [comment]
Dear @herlesupreeth 

Thanks for your replay

I did that but still No internet connection

Here are pcaps and logs:
Core Pcap: 
[No_internet.zip](https://github.com/herlesupreeth/docker_open5gs/files/6315842/No_internet.zip)
Core Log:
[Log.txt](https://github.com/herlesupreeth/docker_open5gs/files/6315852/Log.txt)

**Core Configs:**
[configs.txt](https://github.com/herlesupreeth/docker_open5gs/files/6315882/configs.txt)

**Comment by modyngs** [comment]
also it is pcap from eNB prespective:

[Uploading No int_eNB.zip…]()

**Comment by herlesupreeth** [comment]
You have set wrong IP, rather than 44.102.129.54 its 46.102.129.54

![image](https://user-images.githubusercontent.com/4115839/114830232-516e3b80-9dcc-11eb-830a-6eaf9e80f57a.png)

**Comment by modyngs** [comment]
its not wrong My ip is 46.102.129.156

i changed floating ip as used new VM!

**Comment by herlesupreeth** [comment]
Also, you need to uncomment the ports section in sgwu (please read the README properly, its written to avoid these errors)

![image](https://user-images.githubusercontent.com/4115839/114830608-aca02e00-9dcc-11eb-9b33-e29ec1878d86.png)

**Comment by modyngs** [comment]
Sorry, i thought its just 4G not NSA!
So not changed Sgwu


I changed it, but still not having internet acess on UE!
Thanks
best regards

**Comment by modyngs** [comment]
Do i need to add some route in eNB?

on eNB when i do:
sudo ip r add 172.22.0.6 via 46.102.129.158 

as in readme it says :
ERROR: Nexthup has invalid gateway.

am i doing wrong?

**Comment by herlesupreeth** [comment]
Check the security policies, are you allowing UDP port 2152? do not set UPF_ADVERTISE_IP to 46.102.129.158, keep it same as UPF_IP as you are in 4G only

**Comment by modyngs** [comment]
Its all open
![image](https://user-images.githubusercontent.com/82098055/114834815-2f81b280-9de6-11eb-986c-a233d2d6e055.png)

**Comment by herlesupreeth** [comment]
If you modify .env make sure to run source .env again and bring down the stack and up again before re-tryng

**Comment by modyngs** [comment]
Yea, i  always do that

do u have any other idea?
https://github.com/herlesupreeth/docker_open5gs/issues/33#issuecomment-820207156

**Comment by modyngs** [comment]
Can it be because of the time syncronization?

**Comment by herlesupreeth** [comment]
Post here the output of `ip a` command on the eNB machine. Most likely you may have to change the UE IP allocation range in smf and upf, but lets see

**Comment by modyngs** [comment]
Yea, i think its smf, there are some warning in logs about it,

I'll post ip a here but it is 192.168.1.10/24

**Comment by herlesupreeth** [comment]
i dont think you have to change it as your enp1s0 subnet does not collide with UE subnet

**Comment by modyngs** [comment]
when i turn mobile data on i can see sth like this:
![Screenshot (79)_LI](https://user-images.githubusercontent.com/82098055/114858941-5698ae00-9dff-11eb-9fa4-ad103325eb3e.jpg)

**Comment by modyngs** [comment]
My topology is
eNB( is on Local computer)[192.168.1.10] <==========> Openstack VM { Floating Ip add [46.102.129.185] , Docker Host(Openstack vm) [192.168.1.141] , VOLTE_DOCKERized [172.22.xx.xx] }

1- eNB <===> MME ))))))))) sucess
2- UE )))))))) got connected to network
3- UE can't access internet while i can see 4G sing in one direction!

Dockerized CORE is on the openstack vm[192.168.1.141] with default docker ip[172.22. ...]
eNB is on the Local Coputer with [192.168.1.10]



I will send some logs again!
Its the latest ip and the new Openstack VM,

**Comment by modyngs** [comment]
Also there is sth wrong with time!( maybe because i donot have internet access)

In Ue the time is UTC while in Openstack Vm and eNB its all right to local time!

**Comment by modyngs** [comment]
Can u give me a hint?

**Comment by modyngs** [comment]
Dear @herlesupreeth 
Is'nt it because UE is behind Double NAT? ( as i'm using cloud and docker at the same time over each other for Core)




I also tested your repo[https://github.com/herlesupreeth/docker_open5gs/tree/4g] with 4G branch( Not master) 
Just changed the "DOCKER_HOST_IP" But still do not have internet Access on UE!

Thanks
Best regards

**Comment by modyngs** [comment]
Also changed timezone of all components including dockers, Openstack VM, native ubuntu(for eNB) as ETC/UTC

```
root@ve:~# timedatectl
                      Local time: Sat 2021-04-17 13:33:32 UTC
                  Universal time: Sat 2021-04-17 13:33:32 UTC
                        RTC time: Sat 2021-04-17 13:33:33
                       Time zone: Etc/UTC (UTC, +0000)
       System clock synchronized: yes
systemd-timesyncd.service active: yes
                 RTC in local TZ: no
root@ve:~# docker exec -it 34a2a4672483 /bin/bash
root@34a2a4672483:/open5gs# cat /etc/timezone
Etc/UTC
```

**Comment by modyngs** [comment]
Even UE gets Ip address!
![Screenshot_20210417-150446_Settings](https://user-images.githubusercontent.com/82098055/115117530-483fc300-9fb4-11eb-9622-467e982ccf17.jpg)

**Comment by herlesupreeth** [comment]
I found the reason why you dont have internet access. In the pcap attached here https://github.com/herlesupreeth/docker_open5gs/issues/33#issuecomment-820348977 the S1AP traffic is between NATed IP address or eNB (5.239.89.219) and your EPC at 192.168.1.141. However, the eNB is advertising in s1ap.InitialContextSetupResponse that its transportLayerAddress(IPv4) is 192.168.1.10. As a result of this the GTP traffic in Downlink (EPC to eNB direction) will be sent from 192.168.1.141 to 192.168.1.10 and EPC has no idea where to find 192.168.1.10 resulting in traffic flowing from internet only till EPC and not till eNB.

There are two options to fix this (i.e. if you want to stick with using OpenStack)

1. Create a IPSec VPN link between EPC (VPN server) and eNb (VPN client) and bind the eNB GTP-U and S1AP interface to the VPN tun interface created
2. Or, try adding static route in EPC as follows (although I doubt it will work as there are too many NATs)
`sudo ip r add 192.168.1.10 via 5.239.89.219`

**Comment by modyngs** [comment]
@herlesupreeth 
Thank you so much for your replay,

The 5.239.x.x is the dhcp Ip address from ISP, I do not have Dedicated ip in eNB side ( because i'm using fiber optic which bought  from isp and i'm using modem (By LAN CABLE ) to connect eNB PC to the internet ( My modem has been assigned 192.168.1.10 to PC while Modem gets 5.239.x.x from ISP)

Can u give me hint for creating IPSEC tunnel?

is it possible to solve the issue By changing My Modem Ip address ? for example change 192.168.1.10 to 172.22.x.x which has no conflict with Core Ip address?


Thank you so much  again
Best regard

**Comment by herlesupreeth** [comment]
Will suggest you a fix shortly

**Comment by modyngs** [comment]
It means i cannot add route ( Your second solution ), because it says 

> Nexthop has invalid gateway

**Comment by modyngs** [comment]
> Will suggest you a fix shortly

Thank you so much
just see your message,
please ignore the last message ( i sent it before reding your message)

**Comment by herlesupreeth** [comment]
Use this branch of srsLTE - https://github.com/herlesupreeth/srsLTE/tree/gtpu_addr_advertise

and set `gtp_advertise_addr = 5.239.89.219` your DL traffic issue should be solved (I tested it and it works for me)

**Comment by modyngs** [comment]
wooow,


Thank you so much, i'll try it

**Comment by modyngs** [comment]
@herlesupreeth 

Thank you so much again for your time

I tried different scenarios  according to your SRSLTE repo ( gtp branch)

**{{1}}** in theses scenarios **_I do not have internet access :_**

         UE            =====>>>>>>       SRSLTE    ===>>> ISP DHCP IP add. ===>>>     OPENSTACK     ==>>>          VM
    192.168.100.2       =====>>>>>>  192.168.1.5  ===>>>     5.62.x.x            ===>>>    46.102.129.163  ==>>> 192.168.1.238

1- try to install open5gs Core (Not dockerized ) on cloud and srsLTE on local PC 
2- tried to install Dockerized VOLTE on CLoud and SRSLTE on Local PC


in scenario #1 and #2 i Connected the VM to created Network and then used Floating Ip add. to connect the VM to outside World!
as in bellow picture
![image](https://user-images.githubusercontent.com/82098055/115562627-ec36b080-a2cb-11eb-8f13-7a32288ef3a8.png)




**{{2}}** in theses scenarios **_I have internet access_** 

    UE                =====>>>>>>       SRSLTE    ===>>> ISP DHCP IP add. ===>>>  OPENSTACK VM (Directly Connected To public Dedicated IP)
    192.168.100.2       =====>>>>>>  192.168.1.5  ===>>>     5.62.x.x            ===>>>   46.102.129.163

3- try to install open5gs Core (Not dockerized ) on cloud and srsLTE on local PC 
4- tried to install Dockerized VOLTE on CLoud and SRSLTE on Local PC


in scenario #3 and #4 i Connected the VM directly to PUBLIC IP add. of Openstack ( it just has Floating IP but not local VM ip [192.168.1.x] )

![image](https://user-images.githubusercontent.com/82098055/115562649-f22c9180-a2cb-11eb-8d31-55d633e1312f.png)




SO in All of four scenarios I Used Ur Repo for SRS and Now i have internet access ( in #3 and #4 scenarios)
but as soon as i enable VOLTE on UE this will happen :
![image](https://user-images.githubusercontent.com/82098055/115558419-f8b90a00-a2c7-11eb-9956-87770d227a08.png)


these are my Pcap And logs as Follows
[Log.txt](https://github.com/herlesupreeth/docker_open5gs/files/6351026/Log.txt)
[configs.txt](https://github.com/herlesupreeth/docker_open5gs/files/6351027/configs.txt)
[voolte.zip](https://github.com/herlesupreeth/docker_open5gs/files/6351272/voolte.zip)

**Comment by modyngs** [comment]
I dont think its because i did not used "ROOT" on Vm!
is it?

**Comment by modyngs** [comment]
Hi @herlesupreeth 

Sorry for late replay
Sure i'll do it and send it to you


I'm using your SRSLTE repository ( https://github.com/herlesupreeth/srsLTE/tree/gtpu_addr_advertise )

I also changed the DRB but still the same 
Thanks
Best regards

**Comment by modyngs** [comment]
Also One Note,

When i use your SRS Repo
I cant connect Two USRP to core!
when core is on cloud and RANs are on different local PCs but with the same Global Ip ( ip add. which obtain by HDCP from ISP )

**Comment by modyngs** [comment]
> 2- tried to install Dockerized VOLTE on CLoud and SRSLTE on Local PC
> 
> in scenario #1 and #2 i Connected the VM to created Network and then used Floating Ip add. to connect the VM to outside World!

In Scenario #2 i do not have internet access:

CORE files: 
[Uploading NO_Net_Core.zip…]()
[configs.txt](https://github.com/herlesupreeth/docker_open5gs/files/6414034/configs.txt)
[Log.txt](https://github.com/herlesupreeth/docker_open5gs/files/6414035/Log.txt)


eNB files:

**Comment by modyngs** [comment]
Hi,


> 2- tried to install Dockerized VOLTE on CLoud and SRSLTE on Local PC

Here is my new Try for scenario Number 2

> ```
>    UE            =====>>>>>>     SRSLTE    ===>>>       ISP DHCP IP add.       ===>>>     OPENSTACK     ==>>>          VM
> 192.168.100.2       =====>>>>>>  192.168.1.6  ===>>>     5.74.x.x            ===>>>    46.102.129.185  ==>>> 192.168.1.158
> ```


**I do not have internet connection while i did all of following in both eNB ( on local PC) and Core(Dockerized Volte on cloud)**

```
sudo sysctl net.ipv4.conf.all.forwarding=1
sudo iptables -P FORWARD ACCEPT
sudo sysctl -w net.ipv4.ip_forward=1
sudo iptables -I INPUT --source 10.45.0.0/16 -j ACCEPT
sudo iptables -t nat -I POSTROUTING --out-interface ens3 -j MASQUERADE
sudo iptables -I FORWARD --in-interface ens3 --out-interface ogstun -j ACCEPT
sudo iptables -I FORWARD --in-interface ogstun --out-interface ens3 -j ACCEPT
sudo ufw disable

```
In srsenb i had sth wiered as:




COTS UE is Samsung A42 and SDR is USRP B210
using Cloud [8vCPU,8GBRAM,20GBSSD] for dockerized volte with user "UBUNTU" (not running docker as root ) 
using local PC ( core i7 6700hq,16GBRAM,256GBSSD) for RAN
i'm using srsRAN (Master branch) with UHD ( usrp driver as MASTER branch [uhd v4.])



Core Files:
[Log.txt](https://github.com/herlesupreeth/docker_open5gs/files/6426756/Log.txt)
[configs.txt](https://github.com/herlesupreeth/docker_open5gs/files/6426757/configs.txt)
[volte.zip](https://github.com/herlesupreeth/docker_open5gs/files/6426777/volte.zip)


RAN files:

**Comment by modyngs** [comment]
[srsenblog.txt](https://github.com/herlesupreeth/docker_open5gs/files/6426868/srsenblog.txt)

[Made By SRSRAN.zip](https://github.com/herlesupreeth/docker_open5gs/files/6426921/Made.By.SRSRAN.zip)

**Comment by modyngs** [comment]
> 4- tried to install Dockerized VOLTE on CLoud and SRSLTE on Local PC

Here is My new test For scenario number 4

> ```
> UE                =====>>>>>>       SRSLTE    ===>>> ISP DHCP IP add. ===>>>  OPENSTACK VM (Directly Connected To public Dedicated IP)
> 192.168.100.2       =====>>>>>>  192.168.1.6  ===>>>     5.74.x.x            ===>>>   46.102.129.83
> ```

in this scenario **I have internet access**

as before i did
```
sudo sysctl net.ipv4.conf.all.forwarding=1
sudo iptables -P FORWARD ACCEPT
sudo sysctl -w net.ipv4.ip_forward=1
sudo iptables -I INPUT --source 10.45.0.0/16 -j ACCEPT
sudo iptables -t nat -I POSTROUTING --out-interface ens3 -j MASQUERADE
sudo iptables -I FORWARD --in-interface ens3 --out-interface ogstun -j ACCEPT
sudo iptables -I FORWARD --in-interface ogstun --out-interface ens3 -j ACCEPT
sudo ufw disable
```

_For this Scenario of CORE, I just stopped the VM of scenario number 2 ( which was created few hours ago ) and in OpenStack made Snapshot of that VM. So then Created New VM based on the snapshot but with diffrent Ip address [**this new VM just have Public Ip address** and do not have floating or local Ip] and then signed into it and just changed the .env configs (HOST IP AND SGWU Advertise). then source that and compose up_



So Now the interent is stable
Then i tried to add FOHSS configs through `46.102.129.83:8080`
I did that and Also add ims APN in UE
and then Enabled VOLTE on UE

so Now i can see same connection rnti name ( twice rnti with the same ID ) in srsenb log file
But i can not see any VOLTE sign on UE ( in the past whenever i enabled VOLTE on UE i could see VOLTE Sign on top, beside 4G sign[ data connection ])


COTS UE is Samsung A42 and SDR is USRP B210
using Cloud [8vCPU,8GBRAM,20GBSSD] for dockerized volte with user "UBUNTU" (not running docker as root )
using local PC ( core i7 6700hq,16GBRAM,256GBSSD) for RAN
i'm using srsRAN (Master branch) with UHD ( usrp driver as MASTER branch [uhd v4.])


.
.
.
.


here are Core files:
[Log.txt](https://github.com/herlesupreeth/docker_open5gs/files/6427509/Log.txt)
[configs.txt](https://github.com/herlesupreeth/docker_open5gs/files/6427510/configs.txt)

**Comment by modyngs** [comment]
[configs.zip](https://github.com/herlesupreeth/docker_open5gs/files/6427711/configs.zip)
[Made By srsenb.zip](https://github.com/herlesupreeth/docker_open5gs/files/6427744/Made.By.srsenb.zip)
[enblog.txt](https://github.com/herlesupreeth/docker_open5gs/files/6427827/enblog.txt)
PCAP: https://drive.google.com/file/d/10-GOBwEs5q068Fj9ylnEsp6w302ehY_G/view?usp=sharing


As i said Before My Webui configs are like:
```
---------------------------------------------------------------------------------------------------------------------
| APN      | Type | QCI | ARP | Capability | Vulnerablility | MBR DL/UL(Kbps)     | GBR DL/UL(Kbps) | PGW IP        |
---------------------------------------------------------------------------------------------------------------------
| internet | IPv4 | 9   | 8   | Disabled   | Disabled       | 1GB/1GB |                 |               |
---------------------------------------------------------------------------------------------------------------------
| ims      | IPv4 | 5   | 1   | Disabled   | Disabled       | 3850/1530           |                 |               |
|          |      | 1   | 2   | Enabled    | Enabled        | 128/128             | 128/128         |               |
|          |      | 2   | 4   | Enabled    | Enabled        | 128/128             | 128/128         |               |
---------------------------------------------------------------------------------------------------------------------
```

But in DRB, i Do not have QCI 2! ( as you can see in Configs )





.
.

.


Also FOR FOHSS configuration i followed this
You can see the Diif here:
```
old@old:~/Desktop$ diff a.txt b.txt
59c59
< 2. sip:0198765432101@ims.mnc001.mcc001.3gppnetwork.org
---
> 2. sip:0198765432101
62c62
< Identity = sip:0198765432101@ims.mnc001.mcc001.3gppnetwork.org
---
> Identity = sip:0198765432101
```
[a.txt](https://github.com/herlesupreeth/docker_open5gs/files/6427808/a.txt)
[b.txt](https://github.com/herlesupreeth/docker_open5gs/files/6427818/b.txt)


MY configuration For FOHSS is **_b.txt_**

**Comment by modyngs** [comment]
Can u please Confirm if i'm doing FOHSS and DRB configuration in the right way?

Also Please Lemme Know if Scenario Number 1 and 3 is needed

Thanks
Best regards

**Comment by modyngs** [comment]
I Now Also add QCI 2 in DRB 
and can see these on CORE LOGS:
```
at 105185765
mme          | 05/05 14:56:16.873: [mme] INFO: [Added] Number of MME-Sessions is now 2 (../src/mme/mme-context.c:3234)
sgwc         | 05/05 14:56:16.874: [sgwc] INFO: [Added] Number of SGWC-Sessions is now 2 (../src/sgwc/context.c:849)
sgwu         | 05/05 14:56:16.875: [sgwu] INFO: UE F-SEID[CP:0x3 UP:0x3] (../src/sgwu/context.c:144)
sgwu         | 05/05 14:56:16.875: [sgwu] INFO: [Added] Number of SGWU-Sessions is now 2 (../src/sgwu/context.c:149)
smf          | 05/05 14:56:16.876: [smf] INFO: [Added] Number of SMF-Sessions is now 2 (../src/smf/context.c:2400)
smf          | 05/05 14:56:16.877: [smf] INFO: UE IMSI[001010123456792] APN[ims] IPv4[192.168.101.2] IPv6[] (../src/smf/s5c-handler.c:162)
upf          | 05/05 14:56:16.887: [upf] INFO: [Added] Number of UPF-Sessions is now 2 (../src/upf/context.c:158)
upf          | 05/05 14:56:16.887: [upf] INFO: UE F-SEID[CP:0x3 UP:0x3] APN[ims] PDN-Type[1] IPv4[192.168.101.2] IPv6[] (../src/upf/context.c:339)
smf          | 05/05 14:56:16.888: [smf] WARNING: Unknown PCO ID:(0x2) (../src/smf/context.c:2349)
smf          | 05/05 14:56:16.888: [smf] WARNING: Unknown PCO ID:(0x1a) (../src/smf/context.c:2349)
smf          | 05/05 14:56:16.888: [smf] WARNING: Unknown PCO ID:(0x23) (../src/smf/context.c:2349)
smf          | 05/05 14:56:16.888: [smf] WARNING: Unknown PCO ID:(0x24) (../src/smf/context.c:2349)
pcscf        | 101(134) NOTICE: <script>: PCSCF: REGISTER sip:ims.mnc001.mcc001.3gppnetwork.org (sip:001010123456792@ims.mnc001.mcc001.3gppnetwork.org (192.168.101.2:37723) to sip:001010123456792@ims.mnc001.mcc001.3gppnetwork.org, feE7NyUiEwhq_Jr40wLhXQ..@192.168.101.2)
pcscf        | 101(134) INFO: rr [rr_mod.c:515]: pv_get_route_uri_f(): No route header present.
pcscf        | 101(134) NOTICE: <script>: PCSCF REGISTER:
pcscf        |  Destination URI: <null>
pcscf        |  Request URI: sip:ims.mnc001.mcc001.3gppnetwork.org
pcscf        | 101(134) INFO: rr [rr_mod.c:515]: pv_get_route_uri_f(): No route header present.
pcscf        | 101(134) NOTICE: <script>: Source IP and Port: (192.168.101.2:37723)
pcscf        |  Route-URI:
pcscf        | 101(134) NOTICE: <script>: Received IP and Port: (172.22.0.21:5060)
pcscf        | 101(134) NOTICE: <script>: Contact header: <sip:001010123456792@192.168.101.2:5060>;+sip.instance="<urn:gsma:imei:35132542-524972-0>";q=1.0;+g.3gpp.icsi-ref="urn%3Aurn-7%3A3gpp-service.ims.icsi.mmtel";+g.3gpp.smsip
pcscf        | 101(134) INFO: ims_registrar_pcscf [sec_agree.c:296]: cscf_get_security_verify(): No security-verify parameters found
icscf        | 31(57) INFO: ims_icscf [cxdx_uar.c:71]: create_uaa_return_code(): created AVP successfully : [uaa_return_code]
fhoss        | Exception in thread "Thread-13" java.lang.NullPointerException
fhoss        |  at de.fhg.fokus.hss.cx.op.UAR.processRequest(UAR.java:277)
fhoss        |  at de.fhg.fokus.hss.main.Task.execute(Task.java:169)
fhoss        |  at de.fhg.fokus.hss.main.Worker.run(Worker.java:66)
icscf        | 28(54) ERROR: ims_icscf [cxdx_uar.c:107]: async_cdp_uar_callback(): Error timeout when  sending message via CDP
icscf        | 28(54) WARNING: tm [t_suspend.c:192]: t_continue_helper(): active transaction not found
scscf        |  5(35) DEBUG: ims_dialog [dlg_handlers.c:1923]: print_all_dlgs(): ******************** 5(35) DEBUG: ims_dialog [dlg_handlers.c:1924]: print_all_dlgs(): printing 4096 dialogs
scscf        |  5(35) DEBUG: ims_dialog [dlg_handlers.c:1934]: print_all_dlgs(): ******************** 5(35) DEBUG: ims_auth [authorize.c:187]: reg_await_timer(): Looking for expired/useless at 105185775
scscf        |  5(35) DEBUG: ims_auth [authorize.c:232]: reg_await_timer(): [DONE] Looking for expired/useless at 105185775
```


Looks like there is an error in CDP
ERROR: ims_icscf [cxdx_uar.c:107]: async_cdp_uar_callback(): Error timeout when  sending message via CDP

**Comment by herlesupreeth** [comment]
> I do not have internet connection while i did all of following in both eNB ( on local PC) and Core(Dockerized Volte on cloud)
> 
> sudo sysctl net.ipv4.conf.all.forwarding=1
> sudo iptables -P FORWARD ACCEPT
> sudo sysctl -w net.ipv4.ip_forward=1
> sudo iptables -I INPUT --source 10.45.0.0/16 -j ACCEPT
> sudo iptables -t nat -I POSTROUTING --out-interface ens3 -j MASQUERADE
> sudo iptables -I FORWARD --in-interface ens3 --out-interface ogstun -j ACCEPT
> sudo iptables -I FORWARD --in-interface ogstun --out-interface ens3 -j ACCEPT
> sudo ufw disable
> 

Do NOT run this if you are using docker_open5gs repository as its already been executed inside the container. I dont understand why you are executing the above in eNB (its meaningless, so please dont run it on eNB)

**Comment by herlesupreeth** [comment]
> MY configuration For FOHSS is b.txt

a.txt is the correct one.

**Comment by modyngs** [comment]
> a.txt is the correct one.

Thanks

So this is My FOHSS configs
![image](https://user-images.githubusercontent.com/82098055/117350151-76346b00-aec1-11eb-9b48-3b34a53149f7.png)

**Comment by modyngs** [comment]
Also Add QCI 2 as Follows in srsran/drb.conf

```
{
  qci=2;
  pdcp_config = {
    discard_timer = 100;
    pdcp_sn_size = 12;
  }
  rlc_config = {
    ul_um = {
      sn_field_length = 10;
    };
    dl_um = {
      sn_field_length = 10;
      t_reordering    = 50;
    };
  };
  logical_channel_config = {
    priority = 2;
    prioritized_bit_rate   = -1;
    bucket_size_duration  = 100;
    log_chan_group = 1;
  };
},
```

Yea you are right. i was wrong
In eNB for scenaio number 2 i did that and just repeat it wrongly! wanted just wanted to forward ipv4

In Core run that because i'm using cloud so tried to forward ipv4

Thanks

> I dont understand why you are executing the above in eNB

**Comment by modyngs** [comment]
> a.txt is the correct one.

I run that again But the same thing happened as https://github.com/herlesupreeth/docker_open5gs/issues/33#issuecomment-832695234

**Comment by modyngs** [comment]
dear @herlesupreeth 
Have you managed to check my pcaps or logs?

This is Also My SecurityGroup in openstack

![image](https://user-images.githubusercontent.com/82098055/117400692-6bf18b80-af18-11eb-8af9-71fdeaf6bee7.png)

All are Open

.
.
.

I'm using cloud image for my VM in Openstack [https://cloud-images.ubuntu.com/bionic/current/bionic-server-cloudimg-amd64.img]

Should it be because of that?

**Comment by modyngs** [comment]
Hello again,

We've got The Problem solved by adding IPTABLE in UPF Container

Or you can Fix it before running docker-compose up as bellow:

ADD this to UPF_INIT.SH after python3s
$nano docker_open5gs/upf/upf_init.sh
########################################################################
iptables -t nat -A OUTPUT -p udp -d $SGWU_ADVERTISE_IP --dport 2152 -j DNAT --to-destination $SGWU_IP:2152
########################################################################


Thanks
Best regards

**Comment by herlesupreeth** [comment]
@modyngs I dont think this is needed if UPF and SGWU is running in the same VM. Cam you send me a pcap for this? I mean UE registration pcap

**Comment by modyngs** [comment]
Yea, they are in the same VM, the UPF sends packets to 46.102.143.x while it can not access the interface as UPF advertise IP is Not set for NSA
So this should be forwarded to sgwu and then via SGWU ADVERTISE IP to UE

I'll send it in few minutes. can you also check this ( https://github.com/herlesupreeth/docker_open5gs/issues/37) in between  please?

**Comment by herlesupreeth** [comment]
I have an example pcap here, where eNb is running at 172.30.200.48 and docker_open5gs running at 172.30.200.223. and if you follow the GTP packets from 1359 till 1395 i see UPF properly sending the packets to SGWU internal address and from SGWU to UE via advertised address.
[external_eNB.zip](https://github.com/herlesupreeth/docker_open5gs/files/6538035/external_eNB.zip)

This setup does not use openstack..its purely based on physical machine running in 172.30.200.0/24 subnet

**Comment by modyngs** [comment]
@herlesupreeth 
Hi again

This is the same structure with the same VM on the same Docker, just comment that line
So it is NO NET scenario
[EPC.zip](https://github.com/herlesupreeth/docker_open5gs/files/6538209/EPC.zip)

I'll send the successful Pcap after adding that line on the same VM and same Docker, just add that line


> I have an example pcap here, where eNb is running at 172.30.200.48 and docker_open5gs running at 172.30.200.223. and if you follow the GTP packets from 1359 till 1395 i see UPF properly sending the packets to SGWU internal address and from SGWU to

I think its Not Running Over OpenStack!

**Comment by modyngs** [comment]
[Success.zip](https://github.com/herlesupreeth/docker_open5gs/files/6538315/Success.zip)

Sorry for late

**Comment by modyngs** [comment]
> i see UPF properly sending the packets to SGWU internal address and from SGWU to UE via advertised address.

I do not know whats wrong with Openstack in that case!
but we enter UPF container and saw that packets stuck there!

So u can also add that manually by 
docker exec -it upf /bin/bash
iptables -nvL --line-number && iptables -t nat -nvL --line-number 
iptables -t nat -A OUTPUT -p udp -d 46.102.143.93 --dport 2152 -j DNAT --to-destination 172.22.0.6:2152

**Comment by herlesupreeth** [comment]
Thanks for the pcap, i still dont this issue could arise from using openstack.. looks like a residual NAT rule in your VM

**Comment by modyngs** [comment]
Anytime
@herlesupreeth  as shown here https://github.com/herlesupreeth/docker_open5gs/issues/33#issuecomment-834076145
all policies are open
No restriction

Can you give hint on this issue? https://github.com/herlesupreeth/docker_open5gs/issues/37

Thanks
Best regards

**Comment by modyngs** [comment]
Dear @herlesupreeth

Hi again, Sorry for opening an old issue,

Thanks for you recommendation in  https://github.com/open5gs/open5gs/issues/1341#issuecomment-1020828241

but i saw this issue here that the same problem was solved for SRSLTE in  https://github.com/herlesupreeth/docker_open5gs/issues/33#issuecomment-823348895 by adding GTP Advertise address in SRSLTE repo


I'm using OAI gNB for the RAN and open5GS as my core setup for 5G SA 

the actual setup is now like bellow:
```
      UE      =====>>>>>>         OAI( gNB)      ===>>>   ISP DHCP IP add. (gNB side)   ===>>> OPENSTACK ( VM Floating IP)     ==>>>      VM ( Core_ All open5gs components on a single VM )     

10.45.0.2      =====>>>>>>        192.168.1.6      ===>>>          80.210.x.x            ===>>>         31.7..x.x                  ==>>>        10.10.10.115
```

I've set the Advertise Ip in UPF and all the forwardings are set! but still do not have internet access.

If it is possible to do the same thing on OAI code as done for SRSLTE, that would be really amazing.


Also, I've installed the Quicktun in both sides ( CORE & RAN ) but is there any configurations should be changed in gNB or AMF_UPF ?

Thanks 
Best regards

**Comment by bhuvaneshnexn** [comment]
Dear @herlesupreeth
My UE get connected to dockerized core network, but it does not have internet even my core machine have internet access.
core IP- 172.18.1.225
enb -172.18.1.210
Thanks ,
Bhuvaneshnexn

**Comment by herlesupreeth** [comment]
@bhuvaneshnexn please post a pcap file so that I can get complete picture of the issue. Also, describe your setup, send your .env file used

**Comment by s21sm** [comment]
I had same issue for 5G SA setup. UE registration was OK but no internet access. When my AMF is 

```
amf:
  addr: 10.53.1.2                  # The address or hostname of the AMF.
  bind_addr: 10.53.1.1             # A local IP that the gNB binds to for traffic from the AMF.
```

and my UE IPs are in this range `10.45.0.0/16` (e.g., exactly `10.45.1.2` ) following route to the UE solved my problem

`sudo ip ro add 10.45.0.0/16 via 10.53.1.2`


Now I have internet access on my UE via USRP gNB
